Advanced task for lesson 1
iRootPro/JSADV pull request #3
Opened 2020-05-14 10:01 UTC by iRootPro

2020-05-14 20:30 UTC, arswarog requested changes

2020-05-14 20:30 UTC, arswarog commented on 01_lesson_adv/lengthLine.js
> +console.log(resultText);
К сожалению он обрезает при первой возможности но после maxLength и строка получается больше чем maxLength

2020-05-14 20:30 UTC, arswarog commented on 01_lesson_adv/convertTime.js
> +        min <= 59) {
этот условия для времени например 18:00 am. такое время некорректно, с pm тоже самое

2020-05-15 04:49 UTC, iRootPro commented on 01_lesson_adv/lengthLine.js
> +console.log(resultText);
Нашел ошибку, исправил.
Спасибо.

2020-05-15 04:49 UTC, iRootPro commented on 01_lesson_adv/convertTime.js
> +        min <= 59) {
Исправил, спасибо.

2020-05-15 10:19 UTC, arswarog approved these changes

2020-05-16 17:32 UTC, merged