Add TASK1 and TASK2
iRootPro/JSADV pull request #4
Opened 2020-05-16 17:32 UTC by iRootPro

2020-05-16 18:33 UTC, arswarog requested changes

2020-05-16 18:33 UTC, arswarog commented on 02_lesson/task1.js
> +console.log(inputArray(1, 2, -3, 4, -5))
можно еще проще, попробуй еще, на занятии я рассказывал

2020-05-17 06:42 UTC, iRootPro commented on 02_lesson/task1.js
> +console.log(inputArray(1, 2, -3, 4, -5))
сделал с reduce

2020-05-18 05:21 UTC, arswarog requested changes

2020-05-18 05:21 UTC, arswarog commented on 02_lesson/flight-constrol-system/fcs.js
> +    const allFlights = Object.keys(flights).forEach(flight => {
Искать по всем рейсам не обязательно - в номере билета указан номер рейса

2020-05-18 05:21 UTC, arswarog commented on 02_lesson/flight-constrol-system/fcs.js
> +                }
не советую так писать
```
if (..) {
  throw ...
} else {
  ...
}
```
лучше 
```
if (..) {
  throw ...
} 

...
```

целевой блок кода так же выполнится только когда пройдет все проверки
но новые условия будет проще добавлять. например стоит добавить проверку не заргегестрировался ли уже пассажир?

2020-05-18 05:21 UTC, arswarog commented on 02_lesson/flight-constrol-system/fcs.js
> +        seats: flights[flight].seats,
`* @property {number} countOfSeats Общее количество мест`

2020-05-18 05:21 UTC, arswarog commented on 02_lesson/flight-constrol-system/fcs.js
> +    })
1. лучше использовать filter
2. registeredSeats неиспользуемая переменная, которая всегда имеет значение undefined. она не нужна

2020-05-18 05:21 UTC, arswarog commented on 02_lesson/task1.js
> +    total = arr.reduce((sum, element) => sum += element)
arr не объявлена
объявленная переменная sum не используется. т.к. sum в reduce - это параметр, это своя новая переменная, так же как и element

2020-05-18 19:32 UTC, arswarog approved these changes

2020-05-18 19:32 UTC, arswarog commented on 02_lesson/flight-constrol-system/fcs.js
> +    const allTickets = flights[needFlight].tickets
Стоит добавить проверку на наличие рейса

2020-05-19 08:29 UTC, merged