TASK 3
iRootPro/JSADV pull request #5
Opened 2020-05-18 10:51 UTC by iRootPro

2020-05-18 21:14 UTC, arswarog requested changes

2020-05-18 21:14 UTC, arswarog commented on 02_lesson/adv/codeText.js
> +console.log(count)
в dictionary должны быть только уникальные слова, сейчас там свободно появляются дубликаты

2020-05-19 06:48 UTC, iRootPro commented on 02_lesson/adv/codeText.js
> +console.log(count)
исправил

2020-05-20 05:16 UTC, arswarog approved these changes

2020-05-20 05:16 UTC, arswarog commented on 02_lesson/flight-constrol-system/fcs.js
> +let isRevert = revertTicket('BH118-B50', makeTime(10, 5)) // true
flights[flight].tickets затрудняют чтение кода
В остальном все хорошо!

2020-05-20 05:18 UTC, arswarog approved these changes

2020-05-20 08:42 UTC, merged